kind: Service
apiVersion: v1
metadata:
  name: capstone-2-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: capstone-2
  ports:
    - name: http-port
      targetPort: 80
      port: 80
      nodePort: 30008